CREATE TABLE
	game
(
	id INTEGER NOT NULL IDENTITY,
	date DATE
);

CREATE TABLE
	player
(
	id INTEGER NOT NULL IDENTITY,
	name VARCHAR(255)
);

CREATE TABLE
	team
(
	id INTEGER NOT NULL IDENTITY,
	name VARCHAR(255)
);

CREATE TABLE
	game_team
(
	id INTEGER NOT NULL IDENTITY,
	score INTEGER NOT NULL,
	game_id INTEGER,
	team_id INTEGER,
	CONSTRAINT FK_GAME_TEAM_GAME_ID FOREIGN KEY (game_id) REFERENCES game (id),
	CONSTRAINT FK_GAME_TEAM_TEAM_ID FOREIGN KEY (team_id) REFERENCES team (id)
);

CREATE TABLE
	team_players
(
	team_id INTEGER NOT NULL,
	player_id INTEGER NOT NULL,
	PRIMARY KEY (team_id, player_id),
	CONSTRAINT FK_TEAM_PLAYERS_TEAM_ID FOREIGN KEY (team_id) REFERENCES team (id),
	CONSTRAINT FK_TEAM_PLAYERS_PLAYER_ID FOREIGN KEY (player_id) REFERENCES player (id)
);

CREATE TABLE
	user
(
	username CHAR(30) NOT NULL,
	password CHAR(32) NOT NULL,
	PRIMARY KEY  (username)
);

