CREATE TABLE
	game_team
(
	id INTEGER NOT NULL IDENTITY,
	score INTEGER NOT NULL,
	game_id INTEGER,
	team_id INTEGER,
	CONSTRAINT FK_GAME_TEAM_GAME_ID FOREIGN KEY (game_id) REFERENCES game (id),
	CONSTRAINT FK_GAME_TEAM_TEAM_ID FOREIGN KEY (team_id) REFERENCES team (id)
)
