ALTER TABLE
	team_players
		DROP FOREIGN KEY `FK5AD4FDD0239384A5`,
		DROP FOREIGN KEY `FK5AD4FDD0FDDA9E5`,
		DROP INDEX `FK5AD4FDD0239384A5`,
		DROP INDEX `FK5AD4FDD0FDDA9E5`,
		ADD INDEX `IDX_TEAM_ID` (`team_id`),
		ADD INDEX `IDX_PLAYER_ID` (`player_id`),
		ADD CONSTRAINT `FK_TEAM_PLAYERS_PLAYER_ID` FOREIGN KEY (`player_id`) REFERENCES `player` (`id`),
		ADD CONSTRAINT `FK_TEAM_PLAYERS_TEAM_ID` FOREIGN KEY (`team_id`) REFERENCES `team` (`id`);
