ALTER TABLE
	game_team
		DROP FOREIGN KEY `FK3BAC568A59F8C5C5`,
		DROP FOREIGN KEY `FK3BAC568AFDDA9E5`,
		DROP INDEX `FK3BAC568A59F8C5C5`,
		DROP INDEX `FK3BAC568AFDDA9E5`,
		ADD INDEX `IDX_GAME_ID` (`game_id`),
		ADD INDEX `IDX_TEAM_ID` (`team_id`),
		ADD CONSTRAINT `FK_GAME_TEAM_GAME_ID` FOREIGN KEY (`game_id`) REFERENCES `game` (`id`),
		ADD CONSTRAINT `FK_GAME_TEAM_TEAM_ID` FOREIGN KEY (`team_id`) REFERENCES `team` (`id`);
